title: prettyjellyfish
url: "https://prettyjellyfish.com"
baseurl: ""

permalink: /writing/:year/:slug/

# Collections
collections:
  lab:
    output: true
    permalink: /lab/:slug/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: lab
    values:
      layout: lab

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
